script:

  dataset: 'CEAS_08.csv'
  threaded_training: True
  y_col: 'label'
  drop_columns:
    - "date"
    - "receiver"
  categorical_columns:
    - "sender"
    - "subject"
    - "body"
    - "urls"
    - "label"
  input_path: 'input'
  output_path: 'output'

model:

  bnn:
  
    model_name: "BayesianNeuralNetwork"

    model_1:

        units: 128
        activation: 'relu'
        kernel_initializer: 'he_normal'

    model_2:

        units: 64
        activation: 'relu'
        kernel_initializer: 'he_normal'

    model_3:

        units: 32
        activation: 'relu'
        kernel_initializer: 'he_normal'

  rfc:

    model_name: "RandomForestClassifier"

    model_1:

      n_estimators: 100
      max_depth: 10
      random_state: 42

    model_2:

      n_estimators: 200
      max_depth: 10
      random_state: 42

    model_3:

      n_estimators: 300
      max_depth: 10
      random_state: 42 

  xgb:

    model_name: "XGBClassifier"

    model_1:

      learning_rate: 0.1
      n_estimators: 100
      max_depth: 10

    model_2:
    
      learning_rate: 0.1
      n_estimators: 200
      max_depth: 10 

    model_3:

      learning_rate: 0.1
      n_estimators: 300
      max_depth: 10 
