script:

  dataset: 'CEAS_08.csv'
  threaded_training: True
  y_col: 'label'

  drop_columns:
    - "date"
    - "receiver"
    - "sender"

  categorical_columns:
    - "urls"
    - "label"
    - "subject"
  
  text_columns:
    - "body"

  sender_col: "sender"

  input_path: 'input'
  output_path: 'output'
  
  light_blue: [173, 216, 230]
  light_green: [144, 238, 144]

  pbars:
    
    dataset:
      total: 24
      desc: "Analyzing Dataset"
      position: 0
      
    model:
      total: 3
      desc: "Training Models"
      position: 1

  words:
    - "http://"
    - "https://"
    - "click"
    - "call"
    - "contact"
    - "link"
    - "free"
    - "money"
    - "pay"
    - "debt"

  numbers:

    x-xxx-xxx-xxxx: "\\d{1}\\s*-\\s*\\d{3}\\s*-\\s*\\d{3}\\s*-\\s*\\d{4}"
    xxx-xxx-xxxx: "\\d{3}\\s*-\\s*\\d{3}\\s*-\\s*\\d{4}"
    xxx-xxxx: "\\d{3}\\s*-\\s*\\d{4}"

model:

  mnb:
  
    model_name: "MultinominalNaiveBayes"
    grid_search_params:
      alpha: [0.05, 0.75, 0.1, 0.15]
      fit_prior: [True, False]

  rfc:

    model_name: "RandomForestClassifier"
    grid_search_params:
      n_estimators: [100, 300, 500]
      max_features: ["sqrt", "log2"]

  xgbc:

    model_name: "XGBClassifier"
    grid_search_params:
      learning_rate: [0.1, 0.15]
      n_estimators: [100, 300, 500]
