script:

  dataset: 'CEAS_08.csv'
  threaded_training: True
  y_col: 'label'
  drop_columns:
    - "date"
    - "receiver"
  categorical_columns:
    - "urls"
    - "label"
    - "sender"
    - "subject"
  text_columns:
    - "body"
  input_path: 'input'
  output_path: 'output'
  
  light_blue: [173, 216, 230]
  light_green: [144, 238, 144]

  pbars:
    
    dataset:
      total: 24
      desc: "Analyzing Dataset"
      position: 0
      
    bnn:
      total: 3
      desc: "Training BNN"
      position: 1

    rfc:
      total: 3
      desc: "Training RFC"
      position: 2

    xgbc:
      total: 3
      desc: "Training XGBC"
      position: 3

  words:
    - "http://"
    - "https://"
    - "click"
    - "call"
    - "contact"
    - "link"
    - "free"
    - "money"
    - "pay"
    - "debt"

  numbers:

    x-xxx-xxx-xxxx: "\\d{1}\\s*-\\s*\\d{3}\\s*-\\s*\\d{3}\\s*-\\s*\\d{4}"
    xxx-xxx-xxxx: "\\d{3}\\s*-\\s*\\d{3}\\s*-\\s*\\d{4}"
    xxx-xxxx: "\\d{3}\\s*-\\s*\\d{4}"

model:

  bnn:
  
    model_name: "BayesianNeuralNetwork"

    model_1:

        units: 128
        activation: 'relu'
        kernel_initializer: 'he_normal'

    model_2:

        units: 64
        activation: 'relu'
        kernel_initializer: 'he_normal'

    model_3:

        units: 32
        activation: 'relu'
        kernel_initializer: 'he_normal'

  rfc:

    model_name: "RandomForestClassifier"

    model_1:

      n_estimators: 100
      max_depth: 10
      random_state: 42

    model_2:

      n_estimators: 200
      max_depth: 10
      random_state: 42

    model_3:

      n_estimators: 300
      max_depth: 10
      random_state: 42 

  xgbc:

    model_name: "XGBClassifier"

    model_1:

      learning_rate: 0.1
      n_estimators: 100
      max_depth: 10
      tree_method: 'hist'

    model_2:
    
      learning_rate: 0.1
      n_estimators: 200
      max_depth: 10 
      tree_method: 'hist'

    model_3:

      learning_rate: 0.1
      n_estimators: 300
      max_depth: 10 
      tree_method: 'hist'
