DEBUG: False

LOGGER:
  NAME: "AppLogger"
  LOG_PATH: "log"
  INFO_LOG: "info.log"
  ERROR_LOG: "error.log"
  FORMAT: "[%(asctime)s] %(levelname)s - %(message)s"

MODEL:
  TYPE: "XGBClassifier"
  MODEL_PATH: "model"
  FILES:
    MODEL_FILE: "xgbc_model.joblib"
    URLS_ENCODER: "urls_encoder.joblib"
    SUBJECT_ENCODER: "subject_encoder.joblib"
    DOMAIN_ENCODER: "domain_encoder.joblib"
    BODY_VECTORIZER: "body_vectorizer.joblib"
    
MAIN_WINDOW:
  TITLE: "PyEamil Assistant"
